### ISSUE TITLE
SFX_PlayPatch function prototype parameters don't match the order of its declaration

### ISSUE THREAD

**Issue by AXDOOMER** [nukeykt/PCDoom-v2#11]
`int seq` and `int vol` are inverted in DMX.H. This doesn't match how it is used in DMX.C in the declaration of the function where the function is defined. This doesn't change how the code behaves. 

The offending line: https://github.com/nukeykt/PCDoom-v2/blob/master/DMX.H#L37

You can quickly compare with SFX_SetOrigin which has the seq and vol parameters in the good order.

**Comment by nukeykt** [comment]
Fixed. Thanks!
