### ISSUE TITLE
Remove comment line without comment

### ISSUE THREAD

**Issue by AXDOOMER** [nukeykt/PCDoom-v2#12]
A line has `// ` but there is not comment. This was probably added by mistake, because it's not in the PCDoom-v1 source code. 

https://github.com/nukeykt/PCDoom-v2/blob/546625625a4e93df86f3ac593d53f10328fd101b/p_mobj.c#L584

**Comment by nukeykt** [comment]
This again from the LinuxDoom sources. Let's left this as is.
