### ISSUE TITLE
Add PC Speaker support

### ISSUE THREAD

**Issue by AXDOOMER** [nukeykt/PCDoom-v2#17]
In ASS, there is a way to play PC Speaker sounds from a [MUSE](http://www.shikadi.net/moddingwiki/Muse) format. It's in the source code file `PCFX.C`. 

In Apogee games, the PC Speaker sounds were stored in an [AudioT file](http://www.shikadi.net/moddingwiki/AudioT_Format). The sound data is stored in a format called [Inverse Frequency Sound Format](http://www.shikadi.net/moddingwiki/Inverse_Frequency_Sound_format), which is the direct ancestor of Doom's [PC Speaker sound format](https://doomwiki.org/wiki/PC_speaker_sound_effects).

A document describing the reverse engineered PC Speaker sound format can be found [here](https://www.doomworld.com/idgames/sounds/pcspkr10). All it needs is a conversion to the [Inverse Frequency Sound Format](http://www.shikadi.net/moddingwiki/Inverse_Frequency_Sound_format) before it's sent to ASS to be played.

**Comment by nukeykt** [comment]
Done. Thanks for info!
