### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by fabiensanglard** [nukeykt/PCDoom-v2#18]
i tried to build with DosBox, OpenWatcom and TASM5. I get a linking error message:

"Name must come first"

![screen shot 2017-10-26 at 12 08 37 am](https://user-images.githubusercontent.com/1219472/32121434-769e8ff0-bb11-11e7-90cb-40a591a32cf8.png)

I suspect I don't have the right compiler/assembler. What version are needed?

**Comment by nukeykt** [comment]
Newer versions of TASM seems to be incompatible. I've used TASM v3.1 and open watcom v1.9

**Comment by fabiensanglard** [comment]
I tried to compile with TASM 3.1 but it doesn't work:
(source file open error on /mx):

![screen shot 2017-10-28 at 1 29 40 pm](https://user-images.githubusercontent.com/1219472/32138254-595a02e8-bbe4-11e7-9a43-bbf39ced5064.png)

Building with TASM 1.0 works but the games freeze when starting 3D sequence:

![screen shot 2017-10-28 at 1 28 12 pm](https://user-images.githubusercontent.com/1219472/32138260-6bb73bb8-bbe4-11e7-9eaa-b5e29f791fa8.png)

Are you sure OWatcom 1/9/TASM 3.1 should work?

**Comment by AXDOOMER** [comment]
DOS tools are a bit finicky. If the assembly is not important for you, you may replace the _planar.asm_ rendering code and division code from _i_ibm_a.asm_ with the C version from Chocolate-Doom. There is no C replacement for the DOS joystick input reading code though. That's what I did in [my fork](https://github.com/AXDOOMER/doom-vanille) to save me some trouble, but the game will run ~20% slower. 

I'm looking forward to read your next book!

**Comment by nukeykt** [comment]
I think it is a different assembler. AFAIR, i copied tasm.exe from Borland C++ 3.1 installation.

**Comment by fabiensanglard** [comment]
@AXDOOMER  Thanks :) ! The ASM is important to be, I want to measure how much it improved performances to provide accurate metrics in the book :) !

@nukeykt YES ! TASM from Borland 3.1 DID IT :) ! It runs. Thank you so much for your help !

**Comment by AXDOOMER** [comment]
Interesting. I have Borland C++ 3.1 and it gave me the same result as Fabien posted in his first screenshot. It shows that it's version 4.1 of TASM, not TASM 5.

I found all of this confusing, so I tried to compile PCDoom-v2 **with** the compiled assembly _successfully_ for the first time. 

Screenshot that shows it didn't work with TASM from Borland C++ 3.1: 
![screenshot at 2017-10-28 21-10-52](https://user-images.githubusercontent.com/6194072/32139993-09811178-bc28-11e7-9a5b-123b442a944a.png)

Proof that it's indeed Borland C++ 3.1:![screenshot at 2017-10-28 21-28-14](https://user-images.githubusercontent.com/6194072/32139996-13e10362-bc28-11e7-981b-737440a59577.png)

### Solution

So instead I ran TASM from Borland C++ 2.0, which is version 2.51 and this time it worked!
