### ISSUE TITLE
W_GetNumForName: HELP not found!

### ISSUE THREAD

**Issue by jherrera80** [nukeykt/PCDoom-v2#2]
This is what I get when I select HELP.

**Comment by AXDOOMER** [comment]
Please, verify against https://github.com/Doom-Utils/iwad-patches/raw/master/vanilla-engine/Final%20Doom%20(id%20Anthology)/doom2.exe.

**Comment by jherrera80** [comment]
Ok, didn't know that pcdoom v2 emulated the Final Doom exe. Behavior is correct then.
