### ISSUE TITLE
Music problems

### ISSUE THREAD

**Issue by jherrera80** [nukeykt/PCDoom-v2#3]
The music doesn't sound quite right (like some channels not playing, and the ones that play, sound different). You can test this hearing the music from the first demo in Vanilla and pcdoom. The music volume bar also doesn't seem to be working correctly (the music appears to start at full volume but the bar is at the middle, so when you move the bar, you notice a sudden drop of volume).

**Comment by jherrera80** [comment]
The intro song also sounds clearly different.

**Comment by AXDOOMER** [comment]
DMX is not used, so be aware that OPL will not sound the same.
