### ISSUE TITLE
Provide a project file to build with Open Watcom C

### ISSUE THREAD

**Issue by AXDOOMER** [nukeykt/PCDoom-v2#7]
I'm trying to build it with the IDE and it doesn't work. I got some problems with undefined references. I don't want to use the makefile. I want to do it easy by building with the project open in the IDE.

[pcdoom_build_log.txt](https://github.com/nukeykt/PCDoom-v2/files/857089/pcdoom_build_log.txt)

**Comment by nukeykt** [comment]
I've restructured the contents of most files to match Vanilla Doom disassembly. So some files were removed or renamed. Remove these files and add new ones to the project. I've moved PCDoom to the makefile to match code functions order to Vanilla. It is impossible to do so with project file.

**Comment by AXDOOMER** [comment]
So if I don't compile the source code files in the same order, the internals of the executable will be different?

**Comment by AXDOOMER** [comment]
This is no longer something that I would like. I don't think it's necessary.
