### ISSUE TITLE
PCDoom can't run with 4 mb of RAM

### ISSUE THREAD

**Issue by AXDOOMER** [nukeykt/PCDoom-v2#9]
This bug isn't fixed in PCDoom-v2: https://github.com/nukeykt/pcdoom/issues/4

The message will display unless I set memsize in DosBox to at least `5`. 

https://github.com/nukeykt/PCDoom-v2/blob/546625625a4e93df86f3ac593d53f10328fd101b/i_ibm.c#L1212

Vanilla Doom doesn't display the "insufficient memory" message when `memsize=4`.

The `mem` command is DosBox may be useful if you want to do tests. 

At `4`mb, `mem` will  display:
![untitled](https://cloud.githubusercontent.com/assets/6194072/24172369/5be61cf6-0e5e-11e7-8085-073f22634a8f.png)

**Comment by AXDOOMER** [comment]
The difference comes from the fact that both engines don't see the same amount of memory. 

On this line: https://github.com/nukeykt/PCDoom-v2/blob/546625625a4e93df86f3ac593d53f10328fd101b/i_ibm.c#L1199
They will display different amounts. Vanilla Doom will always display more memory.

**Comment by nukeykt** [comment]
It's due to DOS4GW version. If you copy DOS4GW from Vanilla Doom EXE to PCDoom, it shows more memory. So i can't fix it.

**Comment by AXDOOMER** [comment]
Which version of DOS4GW is that?
